services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m gunicorn app:app
    envVars:
      - key: FIREBASE_CONFIG
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true